use_frameworks!

target 'com.awareframework.ios.sensor.applewatch_Example' do
#  pod 'com.awareframework.ios.sensor.applewatch', :path => '../'
  pod 'com.awareframework.ios.sensor.applewatch', :path => '../'
  pod 'com.awareframework.ios.sensor.locations'
  
  platform :ios, '12.0'
#  use_frameworks!
  target 'com.awareframework.ios.sensor.applewatch_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end

target 'com.awareframework.ios.sensor.applewatch_Example Watch App' do
  #use_frameworks!
  platform :watchos, '8.0'
  pod 'com.awareframework.ios.sensor.applewatch', :path => '../'
end

#target 'com.awareframework.ios.sensor.applewatch_watchos_Example' do
#  pod 'com.awareframework.ios.sensor.applewatch', :path => '../'
#end
